# Generated by Django 4.0.4 on 2022-05-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description dkfgdgfkjlgrfljbfgjgerhjgotughnteognegojeobogrjgnjnglger'),
            preserve_default=False,
        ),
    ]
