# Generated by Django 4.0.4 on 2022-05-19 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_orderitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantiy',
            new_name='quantity',
        ),
    ]
