# Generated by Django 4.0.4 on 2022-05-25 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_payment_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
